[package]
name = "vortex-tui"
version.workspace = true
edition.workspace = true

[dependencies]
vortex-core.workspace = true

crossterm = { workspace = true, features = ["event-stream"] }
futures-util.workspace = true
ratatui.workspace = true
ratatui-textarea.workspace = true
tokio = { workspace = true, features = ["macros"] }
