[package]
name = "vortex-tui"
version.workspace = true
edition.workspace = true

[dependencies]
vortex-core.workspace = true

crossterm = { workspace = true, features = ["event-stream"] }
futures-util.workspace = true
ratatui = { workspace = true, features = ["unstable-rendered-line-info"] }
ratatui-textarea.workspace = true
tokio = { workspace = true, features = ["macros"] }
tui-markdown.workspace = true
